config/routes.rb
CkTask::Application.routes.draw do
  resources :tasks

  resources :people

  resources :task_manager, :only => [:destroy, :index, :show] do
    member do
      put 'finish'
      get 'archive'
    end
  end
  resources :task_manager, :only => [:edit, :new], :controller => :tasks 

end

app/models/person.rb
require 'mini_magick'

class Person < ActiveRecord::Base
  has_many :tasks, :conditions => { :date_finish => nil } 

  IMG_PATH = "public/images/people/"
  IMG_SIZE = '200x200'
  RATIO = { :height => 1, :width => 1 }
  def self.upload_img file
    fn = file.original_filename
    fp = File.join IMG_PATH, fn
    written = File.open(fp, 'wb') { |f| f.write file.read }

    return written
  end

  def self.create_min_image filename

    fp = IMG_PATH + filename
    img = MiniMagick::Image.open(fp)

    crop_image img

    #create miniature
    img.resize IMG_SIZE 
    img.write File.join( IMG_PATH, filename)
  end
  
  def self.crop_image image
    #crop
    rx = image['width'] / RATIO[:width]
    ry = image['height'] / RATIO[:height]

    if rx > ry
      shave_y = 0
      shave_x = (image['width'] - (ry * RATIO[ :width ])) / 2
    else
      shave_y = (image['height'] - (rx * RATIO[ :height ])) / 2
      shave_x = 0
    end

    return image.shave("#{shave_x}x#{shave_y}")
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :person
end

app/models/task_manager.rb
class Task_manager < ActiveRecord::Base
  has_one :person
  has_many :tasks, :through => :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.xml
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.xml
  def create
    Person.upload_img params[:datafile]
    img_fn = params[:datafile].original_filename
    Person.create_min_image img_fn
    params[:person][:img_name] = img_fn

    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to(task_manager_index_path, :notice => 'Osoba zostaa dodana') }
        format.xml  { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update

    @person = Person.find(params[:id])
    
    Person.upload_img params[:datafile]
    img_fn = params[:datafile].original_filename
    Person.create_min_image img_fn
    params[:person][:img_name] = img_fn

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to(@person, :notice => 'Person was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/task_manager_controller.rb
class TaskManagerController < ApplicationController
  def index
    @people = Person.includes( :tasks ).where( :active => true )

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html { render :action => 'show' }
      format.xml { render :xml => @person }
    end
  end

  # DELETE /task_manager/1
  # DELETE /task_manager/1.xml
  def destroy
    @task = Task.find(params[:id])
    task_update = {}
    task_update[:active] = false;
    @task.update_attributes(task_update)
    
    respond_to do |format|
      format.html { redirect_to :back, :flash => { :notice => 'usunieto' } }
      format.xml  { head :ok }
    end
  end

  # PUT /task_manager/1/finish
  # PUT /task_manager/1/finish.xml
  def finish
    @task = Task.find(params[:id])
    task_update = {}
    task_update[:date_finish] = Time.now

    respond_to do |format|
      if @task.update_attributes(task_update)
        format.html { redirect_to :back, :flash => { :notice => 'zadanie przeniesione do archiwum' } }
        format.xml  { head :ok }
      else
        format.html #
        format.xml  #
      end
    end
  end 

  # GET /task_manager/1/archive
  # GET /task_manager/1.xml
  def archive
    @tasks = Task.where( "person_id == ? AND date_finish != ''" , params[:id])

    respond_to do |format|
      format.html # archive.html.erb
      format.xml { render :xml => @tasks }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.xml
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new id = 1
    @task = Task.new
    @people = Person.all

    if params[:person_id].present? then
      @task.person_id = params[:person_id]
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @people = Person.all
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(task_manager_index_path, :notice => 'Zadanie zostalo utworzone') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to( task_manager_index_path , :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_img filename
    return image_tag('people/' + filename, :size => Person::IMG_SIZE, :alt => 'brak obrazu')
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/task_manager_helper.rb
module TaskManagerHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CkTask</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body class="<%= controller.controller_name %> <%= controller.action_name %>">

  <div id="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person, :html => {:multipart => true}) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, :Imie %>
    <%= f.text_field :name %>
  </div>
  <div class="field">


    <%= f.label :datafile, "Zdjęcie" %>
    <%= file_field_tag :datafile %>
  </div>
  <%= f.hidden_field :active, :value=>true %>
  <div class="actions">
    <%= f.submit :Dodaj %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>
<%= show_img @person.img_name %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Person</th>
    <th>Name</th>
    <th>Img</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= show_img person.img_name %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<%= render 'form' %>

<%= link_to 'Powrót', task_manager_index_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Img name:</b>
  <%= @person.img_name %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/task_manager/_add_task_form.html.haml
.add_task_form
  - @task = Task.new
  = link_to "Dodaj", new_task_manager_path( :person_id => add_task_form)

app/views/task_manager/_edit_task_form.html.haml
.task_form
  - task_id = edit_task_form.id
  = link_to "Edytuj", edit_task_manager_path(task_id), :class => "task_edit"
  = link_to "Zakoncz", finish_task_manager_path(task_id), :method => :put, :class => "task_finish"
  /= link_to "Usuń", task_manager_path(task_id), :method => :delete

app/views/task_manager/_task.html.haml
.task{ :id => 'task_id_' + @task.id.to_s}
  .task_date_start= @task.date_start
  .task_desc= @task.desc
  .controlls
    .task_form
      - task_id = @task.id
      = link_to "Edytuj", edit_task_manager_path(task_id), :class => "task_edit"
      = link_to "Zakoncz", finish_task_manager_path(task_id), :method => :put, :class => "task_finish"
.separator

app/views/task_manager/_task_controller.html.haml
.task_controller
  - pages = person.tasks.count/3 -1
  - pages.times do |page|
    = link_to "więcej", :anchor => person.id.to_s + '_' + ((page + 2)*3).to_s

app/views/task_manager/_task_delete.html.haml
.task_delete
  = link_to "Usuń", task_path(task_form), :method => :delete
  

app/views/task_manager/archive.html.haml
= render :partial => 'tasks'
= @tasks.inspect

app/views/task_manager/index.html.haml
#task_manager
  -if flash[:notice]
    .notice
      = flash[:notice]
  -@people.each do |person|

    .person 

      .details 
        .name= person.name
        - if Task.where( "person_id = ? AND date_finish != ''", person.id ).present? 
          .controlls= link_to "Przejdz do Archiwum", archive_task_manager_path( person.id )

        .person_img= show_img person.img_name

      .controlls
        - person_all_tasks_count = Task.all( :conditions => { :person_id => person.id, :active => true }).size

        .add_task_form
          - @task = Task.new
          = link_to "Dodaj", new_task_path( :person_id => person.id )
          /new_task_manager_path( :person_id => person.id ) 

        - if person.tasks.size > 4
          .more_tasks_form
            = link_to "wiecej", task_manager_path(person.id)

      /person tasks show only first 4
      .tasks
        - person.tasks[0..3].each do |task|
          - @task = task
          = render :partial => 'task'

        .clearfix
          /task clearfix
      .clearfix
        /tasks clearfix
    .clearfix
      /person clearfix
= link_to :dodaj_osobe, new_person_path

app/views/task_manager/show.html.haml
#task_manager
  - @tasks = @person.tasks
  .person
    .details 
      .name
        = @person.name
        = link_to("powrot", task_manager_index_path)
      .person_img= show_img @person.img_name
    .controlls
      .less_tasks_form
        = link_to "mniej", task_manager_index_path
    .tasks
      - @tasks.each do |task|
        -@task = task
        = render :partial => 'task'
      .clearfix
    .clearfix
  .clearfix

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc, "Zadanie" %>
    <%= f.text_area :desc, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :person_id, "Dla" %>
    <%= f.select :person_id, @people.map { |p| [p.name, p.id]} %>
  </div>
  <div class="field">
    <%= f.label :date_start, "Rozpoczecie" %>
    <%= f.date_select :date_start %>
  </div>
  <div class="actions">
    <%= f.hidden_field :active, :value=>true %>
    <%= f.submit 'utwórz' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

<%= link_to 'zobacz', @task %> |
<%= link_to 'powrót', task_manager_index_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table border=1>
  <tr>
    <th>Task</th>
    <th>Person</th>
    <th>Desc</th>
    <th>Active</th>
    <th>Date start</th>
    <th>Date finish</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.id %></td>
    <td><%= task.person_id %></td>
    <td><%= task.desc %></td>
    <td><%= task.active %></td>
    <td><%= task.date_start %></td>
    <td><%= task.date_finish %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Person:</b>
  <%= @task.person_id %>
</p>

<p>
  <b>Desc:</b>
  <%= @task.desc %>
</p>

<p>
  <b>Active:</b>
  <%= @task.active %>
</p>

<p>
  <b>Date start:</b>
  <%= @task.date_start %>
</p>

<p>
  <b>Date finish:</b>
  <%= @task.date_finish %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>